Trim obsolete docker images (test-only).
Fixes https://prow.k8s.io/?job=apiserver-network-proxy-push-images

which is failing with:

```
gcloud container images add-tag gcr.io/k8s-staging-kas-network-proxy/proxy-test-client:v20221227-konnectivity-clientv0.0.33-39-g823c619 gcr.io/k8s-staging-kas-network-proxy/proxy-test-client:master
ERROR: (gcloud.builds.submit) build b3da18bb-ff3e-4465-8e2c-058c345d8545 completed with status "FAILURE"
```